### ISSUE TITLE
ns record type support

### ISSUE THREAD

**Issue by wigust** [NorfairKing/dnscheck#1]
Hi.

Thank you for the dnscheck!

Could you to add `ns` record type support, please?

Thanks,
Oleg.

**Comment by NorfairKing** [comment]
Hi @wigust This would be a great addition! See https://hackage.haskell.org/package/dns-4.0.1/docs/Network-DNS-Lookup.html#v:lookupNS if you'd like to add it.

**Comment by NorfairKing** [comment]
@wigust I'm implementing this because it's actually also useful for myself.

**Comment by NorfairKing** [comment]
Now in master.
